services:
  dockerblazorwasmtest_api:
    image: fritzthecat9/dockerblazorwasmtest_api:${SYSTEM_TAG}
    container_name: dockerblazorwasmtest_api
    platform: ${PLATFORM}
    build:
      context: .
      dockerfile: DockerBlazorWASMTest.Api/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ${HOME_VARIABLE}/.aspnet/https:/https/

  dockerblazorwasmtest_blazor:
    image: fritzthecat9/dockerblazorwasmtest_blazor:${SYSTEM_TAG}
    container_name: dockerblazorwasmtest_blazor
    platform: ${PLATFORM}
    build:
      context: .
      dockerfile: DockerBlazorWASMTest.Blazor/Dockerfile
    ports:
      - 7000:80
      - 7001:443
    environment:
      - ASPNETCORE_URLS=https://+:7001;http://+:7000
      - ASPNETCORE_HTTP_PORTS=7000
      - ASPNETCORE_HTTPS_PORTS=7001
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ${HOME_VARIABLE}/.aspnet/https/certificate.crt:/etc/nginx/certificate.crt
      - ${HOME_VARIABLE}/.aspnet/https/private.key:/etc/nginx/private.key
      
  dockerblazorwasmtest_database:
    image: postgres:latest
    container_name: dockerblazorwasmtest_database
    shm_size: 4gb
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: DockerBlazorWASMTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:
    driver: local