// <auto-generated />
using System;
using DockerBlazorWASMTest.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DockerBlazorWASMTest.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240427151450_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DockerBlazorWASMTest.Api.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 4, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Scorching",
                            TemperatureC = 33
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 4, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Cool",
                            TemperatureC = 6
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Balmy",
                            TemperatureC = -15
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Chilly",
                            TemperatureC = 8
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Bracing",
                            TemperatureC = -10
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 5, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Scorching",
                            TemperatureC = 53
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 5, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Freezing",
                            TemperatureC = 25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
